export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const POLL_LIST_REQUEST = "POLL_LIST_REQUEST";
export const POLL_LIST_SUCCESS = "POLL_LIST_SUCCESS";
export const POLL_LIST_ERROR = "POLL_LIST_ERROR";

export const DELETE_POLL_REQUEST = "DELETE_POLL_REQUEST";
export const DELETE_POLL_SUCCESS = "DELETE_POLL_SUCCESS";
export const DELETE_POLL_ERROR = "DELETE_POLL_ERROR";